--- 
services:
  - docker
before_install: 
  - psql -c 'create database knotdb;' -U postgres
  - psql knotdb < api/environtment/travis/db.sql
before_script: 
  - redis-cli config set requirepass 'pass'
  - mv environtment/travis/env.example .env
  - mv environtment/travis/.coveragerc.example .coveragerc
  - mv environtment/travis/run_travis.sh run_travis.sh
  - mv environtment/travis/push.sh push.sh
  - chmod +x run_travis.sh
  - ./run_travis.sh
branches:
  only:
  - test_feature
install: 
  - "cd api"
  - "virtualenv -p python3 env"
  - "source env/bin/activate"
  - "pip install -r requirements.txt"
  - "pip install coverage pytest pytest-cov pytest-ordering testfixtures"
language: python
python: 
  - "3.6"
script: 
  - "pytest --cov=app test/ --ignore=test/ignore/ -vv -s"
services: 
  - postgresql
  - redis
skip_cleanup: true
after_script:
  - kill -9 `cat save_pid.txt`
  - rm save_pid.txt
deploy:
  provider: script
  skip_cleanup: true
  script: bash push
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: test_feature 
    tags: true