--- 
language: python
python: 
  - "3.6"
services: 
  - postgresql
  - redis
  - docker
skip_cleanup: true
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy
  on:
    branch: test_feature 
    tags: true
jobs:
  include:
    - stage: unittest
      script: bash environtment/travis/unittest.sh
stage:
  - name: unittest
    if: branch = devel
  