--- 
language: python
python: 
  - "3.6"
services: 
  - postgresql
  - redis
  - docker
skip_cleanup: true
jobs:
  include:
    - stage: build_database
      script: bash api/environtment/travis/builddb.sh
    - stage: install
      script: bash api/environtment/travis/install.sh
    - stage: unittest
      script: bash environtment/travis/unittest.sh
    - stage: cleanup
      script: bash api/environtment/travis/cleanup.sh
stages:
  - build_database
  - install
  - name: unittest
    if: branch = test_2
  - cleanup
  - stage: deploy
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: bash deploy
      on:
        branch: test_feature 
        tags: true
  