language: python
dist: xenial
python:
  - '3.7'
services:
  - postgresql
jobs:
  include:
    - stage: "Unit Tests"
      script: bash .travis/unit_test.sh
    - stage: "Integration Tests"
      script: bash .travis/integration_test.sh
