--- 
language: python
python: 
  - "3.6"
services: 
  - postgresql
  - redis
  - docker
skip_cleanup: true
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy
  on:
    branch: test_feature 
    tags: true
jobs:
  include:
    - stage: preinstall
      script: bash api/environtment/travis/preinstall.sh
    - stage: setup
      script: bash api/environtment/travis/setup.sh
    - stage: install
      script: bash api/environtment/travis/install.sh
    - stage: unittest
      script: bash api/environtment/travis/unittest.sh
    - stage: cleanup
      script: bash api/environtment/travis/cleanup.sh

stage:
  - preinstall
  - setup
  - install
  - name: unittest
    if: branch = devel
  - name: cleanup
    if: branch = devel
  