--- 
language: python
python: 
  - "3.6"
services: 
  - postgresql
  - redis
  - docker
skip_cleanup: true
jobs:
  include:
    - stage: build_database
      script: bash api/environtment/travis/builddb.sh
    - stage: install
      script: bash api/environtment/travis/install.sh
    - stage: unittest
      script: bash environtment/travis/unittest.sh
    - stage: announce
      script: echo Start Test/Deploy
stages:
  - announce
  - name: build_database
    if: branch = devel
  - name: install
    if: branch = devel
  - name: unittest
    if: branch = devel
deploy:
  provider: script
  skip_cleanup: true
  script: bash api/environtment/travis/deploy.sh
  on:
    tags: true