language: python
python:
  - '3.7'
skip_cleanup: true
services:
  - postgresql
jobs:
  include:
    - stage: unittest
      script: bash .travis/unit_test.sh
    - stage: integration
      script: bash .travis/integration_test.sh
