[tool.black]
extend-exclude = '''
/(
    | cli
)/
'''


[tool.isort]
profile = "black"
known_first_party = "app, dnsagent"
skip_glob = "cli/*"

[tool.pylint.messages_control]
disable = [
  # regex needs to be as is
  "anomalous-backslash-in-string",
  "missing-docstring",
  # trigger false error in recurusive function
  "no-else-return",
  # they are mostly a schema file and configs
  "duplicate-code",
  # line and imports are handled by black
  "line-too-long",
  # short variable is more appropriate in some places
  # such `e` for `error`
  "invalid-name",
  # necessary in decorator
  "broad-except",
  # flask use class boilerplate everywhere
  "no-self-use",
  "too-many-return-statements",
  # mypy needs many validation for `Optional` return type
  "too-many-branches",
  "too-many-statements",
  # misc
  "too-many-locals",
  "too-many-arguments",
  "inconsistent-return-statements",
  "raise-missing-from",
  "fixme",
  # test
  # Test is important as code
  # It makes refactoring a breeze
  "too-few-public-methods",
  # pytest boilerplate
  "no-member",
]

[tool.pylint.master]
ignore-paths = [
    "^api/app/vendors/.*$",
    "^api/tests/load/.*$",
]

[tool.mypy]
ignore_missing_imports = true
exclude = "cli"