version: '0.8.0'
services:
    tarsius:
        build: .
        ports:
          - "5000:5000"
        volumes:
          - .:/app
        command: ["python3","manage.py" ,"server"]
        links:
          - "session"

    session:
        image: redis
        command: ["redis-server", "--requirepass", "tarsius"]
        ports:
          - "6379:6379"

    # database:
    #     image: bitnami/mongodb
    #     environment:
    #       - MONGODB_DATABASE=tarsius_backend
    #       - MONGODB_PASS=tarsius123
    #       - MONGODB_USER=tarsius
    #     ports:
    #       - "27017:27017"