version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: 10.0.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.0.3:9092
