version: '3'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zoo2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      # used to do heartbeats and the session timeout
      ZOOKEEPER_TICK_TIME: 2000
      # limit time to connect to a leader
      ZOOKEEPER_INIT_LIMIT: 5
      # how far out-of-date a server can be from a leader
      ZOOKEEPER_SYNC_LIMIT: 2
      # specify 0.0.0.0 for the current node.
      # zookeper_server_id must match the order of the current node
      # if the current zookeper id is 1, the `0.0.0.0:2888:3888` must be in the 1st order.
      ZOOKEEPER_SERVERS: 10.0.0.1:2888:3888;0.0.0.0:2888:3888;10.0.0.3:2888:3888
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka2
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: 10.0.0.1:2181,10.0.0.2:2181,10.0.0.3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.0.2:9092
