# list of knot servers

# The value here follows the knotc command, not knot.conf
knot_servers:
  master:
    notify:
      - slave1
      - slave2
    acl:
      - slave1
      - slave2
  slave:
    master:
      - master1
    acl:
      - master1


# list of kafka brokers
brokers:
  - "10.0.0.1:9092"
  - "10.0.0.2:9092"
  - "10.0.0.3:9092"
