---
- hosts: knot-slave
  vars:
      restknot_agent_version: 0.7.0
  remote_user: centos

  tasks:
      - name: Install knot DNS
        become: yes
        yum:
            name: knot
            state: present

      - name: Overwrite knot.conf file
        become: yes
        synchronize:
            mode: push
            src: "~/docker-images/{{ item }}"
            dest: "/etc/knot/{{ item }}"
            recursive: yes
        with_items:
            - 'knot.conf'

      - name: Restart knot daemon
        become: yes
        service:
            name: knot
            state: restarted

      - name: Copy docker compose file
        synchronize:
            src: "~/docker-images/{{ item }}"
            dest: "~/docker-images/{{ item }}"
        with_items:
            - 'docker-compose-agent.yml'

      - name: Copy docker images
        synchronize:
            src: "~/docker-images/{{ item }}"
            dest: "~/docker-images/{{ item }}"
        with_items:
            - 'restknot-agent-{{ restknot_agent_version }}.tar'

      - name: load docker images
        command:  docker load -i ~/docker-images/restknot-agent-{{ restknot_agent_version }}.tar

      - name: start containers
        command: docker-compose -f ~/docker-images/docker-compose-agent.yml up -d
