---
- hosts: api

  tasks:
      - name: Copy cockroachdb initial database
        become: yes
        synchronize:
            mode: push
            src: "~/docker-images/cockroachdb/{{ item }}"
            dest: "/{{ item }}"
        with_items:
            # append '/' unless it will created multiple
            # directory
            - 'cockroach-data/'

      - name: Copy docker compose files
        become: yes
        synchronize:
            src: "./configs/{{ item }}"
            dest: "/opt/knot/{{ item }}"
        with_items:
            - 'docker-compose-api.yml'

      - name: pull cockroach image
        command:  docker pull cockroachdb/cockroach:v19.1.5

      - name: pull kafka image
        command:  docker pull wurstmeister/kafka:2.12-2.3.0

      - name: pull zookeper image
        command:  docker pull wurstmeister/zookeeper:latest

      - name: start containers
        become: yes
        command: docker-compose -f /opt/knot/docker-compose-api.yml up -d
