---
- hosts: "{{ target_host }}"

  tasks:
      - name: Install knot DNS
        become: yes
        yum:
            name: knot
            state: present

      - name: Overwrite knot.conf file
        become: yes
        synchronize:
            mode: push
            src: "./configs/{{ item }}"
            dest: "/etc/knot/{{ item }}"
            recursive: yes
        with_items:
            - 'knot.conf.{{ server_type }}'

      - name: Rename knot.conf file
        become: yes
        command: mv /etc/knot/knot.conf.{{ server_type }} /etc/knot/knot.conf

      - name: Restart knot daemon
        become: yes
        service:
            name: knot
            state: restarted

      - name: Copy docker compose file
        become: yes
        synchronize:
            src: "~/docker-images/agent/{{ item }}"
            dest: "/opt/knot/{{ item }}"
        with_items:
            - 'docker-compose.yml'

      - name: Set server type
        become: yes
        replace:
            path: /opt/knot/docker-compose.yml
            regexp: 'RESTKNOT_AGENT_TYPE=master'
            replace: 'RESTKNOT_AGENT_TYPE={{ server_type }}'

      - name: start containers
        become: yes
        command: docker-compose -f /opt/knot/docker-compose.yml up -d
