---
- hosts: "{{ target_host }}"

  tasks:
      - name: Stop knot server
        become: yes
        systemd:
            name: knot
            state: stopped

      - name: stop containers
        become: yes
        command:  docker-compose -f /opt/knot/docker-compose.yml down
