version: '3'
services:
  restknot-agent:
    image: restknot-agent:0.7.0
    environment:
      - RESTKNOT_KNOT_LIB=/usr/lib/x86_64-linux-gnu/libknot.so
      - RESTKNOT_KNOT_SOCKET=/var/run/knot/knot.sock
      - RESTKNOT_KAFKA_BROKER=localhost # using 127.0.0.1 didn't work
      - RESTKNOT_KAFKA_PORTS=9092
      - RESTKNOT_KAFKA_TOPIC=domaindata
      - RESTKNOT_KAFKA_FLAGS=master
      - RESTKNOT_KAFKA_GROUP=cmgz_master
    networks:
      - rknt-agent-net
    entrypoint: dnsagent start master
    volumes:
        - /usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
        - /var/run/knot/:/var/run/knot/
        - /etc/knot/:/etc/knot/
        - /var/lib/knot/:/var/lib/knot/

networks:
  rknt-agent-net:
    driver: bridge
