version: '3'
services:
  knot:
    image: registry.gitlab.com/biznetgio/knot_agent:1.1.8
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=6967
      - KNOT_LIB=libknot.so
      - MASTER_HOST=10.10.3.29
      - MASTER_PORT=6968
      - NAME_HOST=cmg01z00knsl001
      - STATUS_AGENT='slave'
      - FLASK_DEBUG=True
    volumes:
      - .:/app
      - /etc/knot/knot.conf:/etc/knot/knot.conf
      - /var/lib/knot:/var/lib/knot
      - /var/run/knot:/run/knot/
    # command: gunicorn production:app -b 0.0.0.0:6967 --reload --log-level debug
    command: python3 manage.py server
    ports:
      - "6967:6967"