version: '0.5.6'
services:
  knot:
    image: biznetgio/knot_agent
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=6967
      - KNOT_LIB=libknot.so
      - MASTER_HOST='' # ip master target
      - MASTER_PORT='' # port master target
      - NAME_HOST='' # knot host
      - STATUS_AGENT='' # master or slave
    volumes:
      - /etc/knot/knot.conf:/etc/knot/knot.conf
      - /var/lib/knot:/var/lib/knot
      - /var/run/knot:/run/knot/
    command: sh run.sh server production 2
    ports:
      - "6967:6967"