version: '3'
services:
  restknot-agent:
    image: restknot-agent:0.7.0
    environment:
      - RESTKNOT_KNOT_LIB=libknot.so
      - RESTKNOT_KNOT_SOCKET=/var/run/knot/knot.sock
      - RESTKNOT_KAFKA_BROKER=127.0.0.1
      - RESTKNOT_KAFKA_PORTS=9092
      - RESTKNOT_KAFKA_TOPIC=domaindata
      - RESTKNOT_KAFKA_FLAGS=master
      - RESTKNOT_KAFKA_GROUP=cmgz_master
    entrypoint:
      - dnsagent
      - start
      - master
