#!/usr/bin/env -S just --justfile

alias f := fmt
alias l := lint

# List available commands.
_default:
    just --list --unsorted

# Setup the repository.
setup:
    rye sync

# Tasks to make the code-base comply with the rules. Mostly used in git hooks.
comply: fmt lint

# Check if the repository comply with the rules and ready to be pushed.
check: fmt-check lint

# Build the container image.
image-build:
    docker build --tag restknot-agent:latest --build-arg VCS_REVISION=$(git rev-parse --short HEAD) .

# Run the container image.
image-start:
    docker compose up -d

# Stop the container image.
image-stop:
    docker compose down

# Format the codebase.
fmt:
    rye fmt

# Check is the codebase properly formatted.
fmt-check:
    rye fmt --check

# Lint the codebase.
lint:
    rye lint

# Check dependencies health.
up:
    rye sync --update-all
