[tool.poetry]
name = "agent"
version = "0.7.12"
description = "RESTKnot Agent"
authors = ["Azzam S.A <azzam@biznetgio.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
confluent-kafka = "1.7.0"
libknot = "3.2.1"
PyYAML = "6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-mock = "^3.10.0"
black = "^22.10.0"
ruff = "^0.0.85"
isort = "^5.12.0"

[tool.isort]
profile = "black"
known_first_party = "app"

[tool.ruff]
ignore = [
  "E501",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
