version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka:6.1.1
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: 10.10.10.10:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://20.20.20.20:9092
