all:
  vars:
    ansible_user: "centos"
    ansible_private_key_file: "~/ssh-keys/vm-key.pem"
    owner: "centos"

api:
  hosts:
    10.0.0.1:
      host_ip: "10.0.0.1"

master:
  vars:
    server_type: "master"
  hosts:
    10.0.0.2:
      broker_group_id: "master1"

slave:
  vars:
    server_type: "slave"
  hosts:
    10.0.0.3:
      broker_group_id: "slave1"
