---
- hosts: api

  tasks:
    - name: Create app directory
      become: yes
      file:
        path: /opt/knot
        state: directory

    - name: Create data directory
      become: yes
      file:
        path: /opt/knot/data
        state: directory

    - name: Change ownership of knot
      become: yes
      file:
        path: /opt/knot
        owner: '{{ owner }}'
        group: '{{ owner }}'

    - name: Change ownership of data
      become: yes
      file:
        path: /opt/knot/data
        owner: 1000
        group: 1000

    - name: Copy required files
      synchronize:
        src: "./configs/api/{{ item }}"
        dest: "/opt/knot/{{ item }}"
      with_items:
        - "docker-compose.yml"
        - "kowl.yml"
        - "schema.sql"

    - name: Check if docker exists
      # changing PATH is dangerous. it's bettter to
      # just use a full path
      command: ~/.local/bin/docker-compose -v
      args:
        chdir: /opt/knot

    - name: Start containers
      command: ~/.local/bin/docker-compose up -d
      args:
        chdir: /opt/knot

    - name: Create database
      command: docker run --rm cockroachdb/cockroach:v19.2.2 sql --host='{{ host_ip }}':26257 --insecure --execute "CREATE DATABASE IF NOT EXISTS knotdb;"

    - name: Create table
      command: cat /opt/knot/schema.sql | docker run -i --rm cockroachdb/cockroach:v19.2.2 sql --host='{{ host_ip }}':26257 --insecure --database=knotdb

    - name: Create broker topic
      command: docker run --rm confluentinc/cp-kafka:6.2.0 kafka-topics --create --topic domaindata --partitions 1 --replication-factor 3 --if-not-exists --bootstrap-server '{{ host_ip }}':9092
