version: '0.8.0'
services:
    web:
        build: .
        ports:
          - "6969:6969"
        volumes:
          - .:/app
        environment:
          - APP_HOST=0.0.0.0
          - APP_PORT=6969
          - FLASK_DEBUG=True
          - APP_REDIS_URL=redis://:pass@session:6379/0
          - CELERY_BROKER_URL=amqp://admin:qazwsx@rabbitmq:5672//
          - CELERY_RESULT_BACKEND=amqp://admin:qazwsx@rabbitmq:5672//
          - WORKER=2
          - ENVIRONMENT=development
          - COMMAND=server
        command: ["bash","run.sh"]
        links:
          - "session"
          - "rabbitmq"

    session:
        image: redis
        command: ["redis-server", "--requirepass", "pass"]
        ports:
          - "6379:6379"

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "qazwsx"
            RABBITMQ_DEFAULT_VHOST: "/"
        user: nobody
        ports:
            - "15672:15672"
            - "5672:5672"

    celeryneo:
        image: neo-openstack-v2_web
        environment:
          - C_FORCE_ROOT=true
          - APP_HOST=0.0.0.0
          - APP_PORT=6969
          - FLASK_DEBUG=True
          - APP_REDIS_URL=redis://:pass@session:6379/0
          - CELERY_BROKER_URL=amqp://admin:qazwsx@rabbitmq:5672//
          - CELERY_RESULT_BACKEND=amqp://admin:qazwsx@rabbitmq:5672//
        user: nobody
        command: ["bash","celery.sh" ,"2"]
        volumes:
          - .:/app
        links:
          - "session"
          - "rabbitmq"
