version: '0.5.4'
services:
    restknot:
        image: registry.gitlab.com/biznetgio/restknot:1.1.0
        ports:
          - "6968:5000"
        environment:
          - APP_HOST=0.0.0.0
          - APP_PORT=5000
          - DB_NAME=knotdb
          - DB_HOST=10.10.3.32
          - DB_PORT=26257
          - DB_USER=root
          - DB_PASSWORD=
          - DB_SSL=disable
          - SOCKET_AGENT_HOST=http://10.10.3.42
          - SOCKET_AGENT_PORT=6967
          - ACL=127.0.0.1/24, 103.77.104.199/24, 10.150.24.11/24, 182.253.68.106/24, 180.249.0.28/24, 172.17.0.1/24
          - FLASK_REDIS_URL=redis://:pass@session:6379/0
          - WORKER=2
          - ENVIRONMENT=production
          - COMMAND=server
        command: ["sh","run.sh"]
        links:
          - "session"
          # - "db"
          # - "db2"

    session:
        image: redis
        command: ["redis-server", "--requirepass", "pass"]
        ports:
          - "6379:6379"

    # db:
    #   image: cockroachdb/cockroach
    #   volumes:
    #     - db:/cockroach/cockroach-data
    #   command: start --insecure --advertise-addr=db --cache=.25 --max-sql-memory=.25
    #   ports:
    #     - "26257:26257"
    #     - "26256:8080"
    # db2:
    #   image: cockroachdb/cockroach
    #   command: start --advertise-host=db2 --join=db:26257 --cache=.25 --max-sql-memory=.25 --insecure
    #   volumes:
    #      - db2:/cockroach/cockroach-data
    #   ports:
    #     - "26258:26257"
    #   links:
    #       - "db"