version: '0.5.6'
services:
    restknot:
        image: registry.gitlab.com/biznetgio/restknot:1.2.0
        ports:
          - "6968:5000"
        environment:
          - APP_HOST=0.0.0.0
          - APP_PORT=5000
          - DB_NAME=knotdb
          - DB_HOST=localhost
          - DB_PORT=26257
          - DB_USER=root
          - DB_PASSWORD=
          - DB_SSL=disable
          - SOCKET_AGENT_HOST='http://127.0.0.1'
          - SOCKET_AGENT_PORT=6967
          - ACL='127.0.0.1/24, 127.0.0.1/24'
          - FLASK_REDIS_URL=redis://:pass@localhost:6379/0
          - WORKER=2
          - ENVIRONMENT=production
          - COMMAND=server
          - DEFAULT_NS='' # eg. 'ns1.example.com.' or 'ns1.example.com. ns2.example.com.' 
          - DEFAULT_SOA_CONTENT='' # eg. 'one.dns.id.' or 'one.dns.id. hostmaster.dns.id.'
          - DEFAULT_SOA_SERIAL='' # eg. '10800 3600 604800 38400'
          - CELERY_BROKER_URL="amqp://admin:pass@localhost:5672//"
          - CELERY_RESULT_BACKEND="amqp://admin:pass@localhost:5672//"
        command: ["sh","run.sh"]
        links:
          - "session"
          - "rabbitmq"

    celery:
        image: registry.gitlab.com/biznetgio/restknot:1.2.0
        ports:
          - "6968:5000"
        environment:
          - APP_HOST=0.0.0.0
          - APP_PORT=5000
          - DB_NAME=knotdb
          - DB_HOST=localhost
          - DB_PORT=26257
          - DB_USER=root
          - DB_PASSWORD=
          - DB_SSL=disable
          - SOCKET_AGENT_HOST=http://127.0.0.1
          - SOCKET_AGENT_PORT=6967
          - ACL='127.0.0.1/24, 127.0.0.1/24'
          - FLASK_REDIS_URL=redis://:pass@localhost:6379/0
          - WORKER=2
          - ENVIRONMENT=production
          - COMMAND=server
          - DEFAULT_NS='' # eg. 'ns1.example.com.' or 'ns1.example.com. ns2.example.com.' 
          - DEFAULT_SOA_CONTENT='' # eg. 'one.dns.id.' or 'one.dns.id. hostmaster.dns.id.'
          - DEFAULT_SOA_SERIAL='' # eg. '10800 3600 604800 38400'
          - CELERY_BROKER_URL="amqp://admin:pass@localhost:5672//"
          - CELERY_RESULT_BACKEND="amqp://admin:pass@localhost:5672//"
        command: ["sh","celery.sh", "2"]
        links:
          - "session"
          - "rabbitmq"

    session:
        image: redis
        command: ["redis-server", "--requirepass", "pass"]
        ports:
          - "6379:6379"

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "qazwsx"
            RABBITMQ_DEFAULT_VHOST: "/"
        user: nobody
        ports:
            - "15672:15672"
            - "5672:5672"