version: '3'
services:
  restknot-api:
    image: biznetgio/restknot-api:0.7.8
    # depends_on:
    #   - kafka1
    ports:
      - '5000:5000'
    environment:
      - TZ=Asia/Jakarta
      - FLASK_APP=autoapp.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0

      # server
      - APP_HOST=0.0.0.0 # default 0.0.0.0
      - APP_PORT=5000 # default 8000

      - DB_NAME=knotdb # don't add whitespace beetween =
      - DB_HOST=roach
      - DB_PORT=26257
      - DB_USER=root
      - DB_SSL=disable

      # topic to suscribe
      - RESTKNOT_KAFKA_TOPIC=domaindata

      # don't add quote, otherwise it will not work
      # <MNAME> <RNAME> <without serial!> <refresh> <retry> <expire> <minimum>
      - DEFAULT_SOA_RDATA=one.dns.id. hostmaster.dns.id. 3600 1800 604800 86400
      - DEFAULT_NS=one.dns.id. two.dns.id.

      - RESTKNOT_API_KEY=123
      # set config file location. `config.yml` is the default
      # - RESTKNOT_CONFIG_FILE=

    # default timeout:30
    command: gunicorn 'autoapp:app' -c 'gunicorn.conf.py' --timeout 60
