version: '0.5.6'
services:
    restknot:
        image: biznetgio/knot_api
        ports:
          - "6968:5000"
        environment:
          - APP_HOST=0.0.0.0
          - APP_PORT=5000
          - DB_NAME=knotdb
          - DB_HOST=localhost
          - DB_PORT=26257
          - DB_USER=root
          - DB_PASSWORD=
          - DB_SSL=disable
          - SOCKET_AGENT_HOST='http://10.10.3.42'
          - SOCKET_AGENT_PORT=6967
          - ACL='127.0.0.1/24, 103.77.104.199/24, 10.150.24.11/24, 182.253.68.106/24, 180.249.0.28/24, 172.17.0.1/24'
          - FLASK_REDIS_URL=redis://:pass@session:6379/0
          - WORKER=2
          - ENVIRONMENT=production
          - COMMAND=server
          - DEFAULT_NS='satu.neodns.id. dua.neodns.id.'
          - DEFAULT_SOA_CONTENT='satu.neodns.id. hostmaster.neodns.id.'
          - DEFAULT_SOA_SERIAL='10800 3600 604800 38400'
          - CELERY_BROKER_URL="amqp://admin:qazwsx@rabbitmq:5672//"
          - CELERY_RESULT_BACKEND="amqp://admin:qazwsx@rabbitmq:5672//"
        command: ["sh","run.sh"]
        links:
          - "session"

    session:
        image: redis
        command: ["redis-server", "--requirepass", "pass"]
        ports:
          - "6379:6379"