FROM alpine
MAINTAINER Sofyan Saputra "sofyan@biznetgio.com"


RUN apk update && \
    mkdir /app
COPY . /app
WORKDIR /app
RUN apk --no-cache add build-base bash git openssl openssl-dev libxslt-dev linux-headers libffi-dev
RUN apk --no-cache add python3 python3-dev
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN pip3 install gunicorn
RUN apk del build-base
EXPOSE 6969