version: '3'
services:
    restknot-api:
        image: restknot-api:0.7.0
        ports:
            - '5000:5000'
        environment:
            - FLASK_APP=autoapp.py
            - FLASK_ENV=production
            - GUNICORN_WORKERS= 4
            - FLASK_DEBUG=0
            - APP_HOST=0.0.0.0
            - APP_PORT=5000
            - DB_NAME=knotdb # don't add whitespace beetween =
            - DB_HOST=roach1
            - DB_PORT=26257
            - DB_USER=root
            - DB_SSL=disable
            - KAFKA_HOST=127.0.0.1
            - KAFKA_PORT=9092
            # don't add quote, otherwise it will not work
            - DEFAULT_SOA_CONTENT=satu.neodns.id. hostmaster.neodns.id.
            - DEFAULT_SOA_SERIAL=3600 1800 604800 86400
            - DEFAULT_NS=satu.neodns.id. dua.neodns.id.
            # change according to your yaml server config location
            - RESTKNOT_CLUSTER_FILE=/rknt/servers.yaml
        volumes:
            - ~/.config/restknot/:/rknt
        links:
            - zookeeper
            - kafka
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    roach1:
        image: cockroachdb/cockroach:v19.1.5
        command: start --insecure
        ports:
          - "26257:26257"
        volumes:
          - ./cockroach-data/roach1:/cockroach/cockroach-data
    roach-init:
        image: bgn/cockroach:v19.1.5
        entrypoint: /cockroach/init-db.sh
        command: init
        depends_on:
            - roach-one
