version: '3'
services:
    restknot-api:
        image: biznetgio/restknot-api:0.7.0
        ports:
            - '5000:5000'
        environment:
            - TZ=Asia/Jakarta
            - FLASK_APP=autoapp.py
            - FLASK_ENV=production
            - GUNICORN_WORKERS=4
            - FLASK_DEBUG=0
            - APP_HOST=0.0.0.0
            - APP_PORT=5000
            - DB_NAME=knotdb # don't add whitespace beetween =
            - DB_HOST=roach
            - DB_PORT=26257
            - DB_USER=root
            - DB_SSL=disable
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - RESTKNOT_KAFKA_TOPIC=domaindata
            # don't add quote, otherwise it will not work
            # <MNAME> <RNAME> <without serial!> <refresh> <retry> <expire> <minimum>
            - DEFAULT_SOA_RDATA=satu.neodns.id. hostmaster.neodns.id. 3600 1800 604800 86400
            - DEFAULT_NS=satu.neodns.id. dua.neodns.id.
            # change according to your yaml server config location
            - RESTKNOT_CLUSTER_FILE=/rknt/servers.yaml
            - RESTKNOT_API_KEY=123
        command: gunicorn 'autoapp:app' -b '0.0.0.0:5000' -w 4
        volumes:
            # on CentOS family you need to add `:Z`
            - ~/.config/restknot/:/rknt:Z
            - ~/restknot-data/:/restknot-data:Z
        links:
            - zookeeper
            - kafka
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    roach:
        image: cockroachdb/cockroach:v19.1.5
        command: start --insecure
        ports:
          - "26257:26257"
        volumes:
          - /cockroach-data:/cockroach/cockroach-data:Z

