version: 0.8.0
services:
    web:
        build: .
        ports:
            - '5000:5000'
        volumes:
            - '.:/app'
        environment:
            - APP_HOST=0.0.0.0
            - APP_PORT=5000
            - FLASK_DEBUG=True
            - WORKER=2
            - ENVIRONMENT=development
            - COMMAND=server
        command:
            - bash
            - run.sh
        links:
            - zookeeper
            - kafka
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
