name: CI

on: [push, pull_request]

jobs:

  code_quality:
    name: Code Quality
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@dprint
    - uses: taiki-e/install-action@v2
      with:
        tool: typos-cli

    - name: Lint
      # currently cli is not-maintained
      run: |
        just check
