name: CI (Agent)

env:
  VENV_PATH: "~/.venv-agent"

on:
  push:
    paths:
      -  agent/**
      - .github/workflows/ci_agent.yml
  pull_request:
    paths:
      -  agent/**
      - .github/workflows/ci_agent.yml


defaults:
  run:
    working-directory: agent

jobs:

  code_quality:
    name: Code Quality
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11.3'

    - name: Cache poetry install
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: poetry

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ${{ env.VENV_PATH }}

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ${{ env.VENV_PATH }}
        key: venv-agent-${{ hashFiles('**/poetry.lock') }}

    - name: Install confluent-kafka prerequisites
      run: |
        sudo apt-get install --yes gcc librdkafka-dev python3-dev

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@dprint

    - name: Lint
      # currently cli is not-maintained
      run: |
        just fmt-check
        just lint
