name: CI (Agent)

on:
  push:
    paths:
      -  agent/**
      - .github/workflows/ci_agent.yml
  pull_request:
    paths:
      -  agent/**
      - .github/workflows/ci_agent.yml


defaults:
  run:
    working-directory: agent

jobs:

  code_quality:
    name: Code Quality
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true

    - name: Install confluent-kafka prerequisites
      run: |
        sudo apt-get install --yes gcc librdkafka-dev python3-dev

    - name: Sync dependencies
      run: rye sync

    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@dprint

    - name: Lint
      # currently cli is not-maintained
      run: just check
