name: CI (API)

env:
  MIN_SUPPORTED_RUST_VERSION: "1.68.0"

on:
  push:
    paths:
      -  api/**
      - .github/workflows/ci_api.yml
  pull_request:
    paths:
      -  api/**
      - .github/workflows/ci_api.yml


defaults:
  run:
    working-directory: api

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest dprint release
        uses: taiki-e/install-action@dprint

      - name: Ensure `fmt` has been run
        run:  just fmt-check

      - name: Ensure MSRV is set in `clippy.toml`
        run: grep "^msrv = \"${{ env.MIN_SUPPORTED_RUST_VERSION }}\"\$" clippy.toml

      - name: Run clippy
        env:
          SQLX_OFFLINE: true
        run: just lint

  msrv:
    name: Minimum supported rust version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rust toolchain (v${{ env.MIN_SUPPORTED_RUST_VERSION }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Prepare the environment variables
        run: |
          cp .example.env .env

      - name: Prepare the database
        env:
          PGPASSWORD: secret
        run: |
          # Start the database
          docker-compose --file tests/docker-compose.yml run --detach --name db db
          # Check DB version
          docker exec db /cockroach/cockroach version
          # Create a db
          docker exec db /cockroach/cockroach sql --insecure  --execute "create database knot;"
          # Improt a schema
          docker exec db /cockroach/cockroach sql --insecure --database knot < db/schema.sql

      - name: Run tests
        env:
          DATABASE_URL: postgres://root@localhost:26257/knot
        run: just test

  build:
    name: Build for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { build: linux-gnu,  os: ubuntu-22.04, target: x86_64-unknown-linux-gnu    }
          # - { build: win-gnu,    os: windows-2022, target: x86_64-pc-windows-gnu       }
          # - { build: win-msvc,   os: windows-2022, target: x86_64-pc-windows-msvc      }
          # - { build: win32-msvc, os: windows-2022, target: i686-pc-windows-msvc        }
          # - { build: macos,      os: macos-12    , target: x86_64-apple-darwin         }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Show version information
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Install musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            --allow-unauthenticated musl-tools

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}
