name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
 api:
    name: Push restknot-api image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        projects:
          - {image: "restknot-api", directory: "api" }
          - {image: "restknot-agent", directory: "agent" }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare env
        # the common usage of short SHA is 7 characters
        run: |
          echo "BUILD_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Show env
        run: |
          echo "BUILD_VERSION is: ${{ env.BUILD_VERSION }}"

      - name: Prepare necessary files
        run: |
          # use default location, instead setting the `RESTKNOT_CONFIG_FILE`
          cp  api/config.example.yml api/config.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: biznetgio/${{ matrix.projects.image }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.projects.directory }}
          file: ./${{ matrix.projects.directory }}/Dockerfile
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

